window.CHEM_MASTER = {
  "_note": "Snapshot of chemical master (REI/PHI/quantity per acre). Provided by Lenny on 2026-04-29. Update or replace with live sheet fetch once master tab is identified.",
  "_columns": [
    "EntryID",
    "ItemName",
    "Farm",
    "LabelDate",
    "RegistrationNumber",
    "ActiveIngredient",
    "Target",
    "ApplicationMethod",
    "FRAC",
    "IRAC",
    "NumberOfApplicationsPerSeason",
    "MaximumUsagePerSeason",
    "QuantityPerAcre",
    "PerAcreUnits",
    "PHIDays",
    "REIHours",
    "Notes"
  ],
  "rows": [
    {
      "EntryID": "0dosedqi",
      "ItemName": "Torino",
      "Farm": "Lettuce",
      "RegistrationNumber": "8033-103-10163",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 8.5,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "0e03dk5m",
      "ItemName": "Regalia Biofungicide",
      "Farm": "Cuke",
      "RegistrationNumber": "84059-3",
      "ApplicationMethod": "Drip, Spray",
      "QuantityPerAcre": 1.9,
      "PerAcreUnits": "gallons",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "0m6qy09z",
      "ItemName": "Luna Experience",
      "Farm": "Lettuce",
      "RegistrationNumber": "264-1091",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 42.5,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 7,
      "REIHours": 12
    },
    {
      "EntryID": "123feee8",
      "ItemName": "Hexygon",
      "Farm": "Cuke",
      "RegistrationNumber": "10163-251",
      "ApplicationMethod": "Spray",
      "PHIDays": 1,
      "REIHours": 12
    },
    {
      "EntryID": "133aa09e",
      "ItemName": "Dupont Fontellis",
      "Farm": "Cuke",
      "RegistrationNumber": "352-834",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 16,
      "PerAcreUnits": "ounces",
      "PHIDays": 1,
      "REIHours": 12
    },
    {
      "EntryID": "16xyaeg3",
      "ItemName": "Sovran",
      "Farm": "Cuke",
      "RegistrationNumber": "7969-154",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 4.8,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "18db5385",
      "ItemName": "Natural Wet",
      "Farm": "Cuke",
      "ApplicationMethod": "Drip",
      "QuantityPerAcre": 16,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 0
    },
    {
      "EntryID": "25f3fc0d",
      "ItemName": "Pyganic 5.0",
      "Farm": "Cuke",
      "RegistrationNumber": "1021-1772",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 102,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "27673b94",
      "ItemName": "Azatin O",
      "Farm": "Lettuce",
      "RegistrationNumber": "70051-9-59807",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 24,
      "PerAcreUnits": "milliliters",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "31a73f64",
      "ItemName": "Dipel DF",
      "Farm": "Lettuce",
      "RegistrationNumber": "73049-39",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 5,
      "PerAcreUnits": "pounds",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "34xmqcnv",
      "ItemName": "Torino",
      "Farm": "Cuke",
      "RegistrationNumber": "8033-103-10163",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 3.4,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "373c6b1a",
      "ItemName": "Azatin O (Lettuce)",
      "Farm": "Lettuce",
      "RegistrationNumber": "70051-9-59807",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 20,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "37b29dba",
      "ItemName": "Debug",
      "Farm": "Lettuce",
      "RegistrationNumber": "70310-5",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 260,
      "PerAcreUnits": "gallons",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "3cfe4361",
      "ItemName": "Merivon(R) Xemium(R)",
      "Farm": "Lettuce",
      "RegistrationNumber": "7969-310",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 13.75,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "3e7009b1",
      "ItemName": "BotaniGard ES",
      "Farm": "Lettuce",
      "RegistrationNumber": "82074-1",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 7.5,
      "PerAcreUnits": "quarts",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "3f3d478d",
      "ItemName": "Marrone Bio Venerate CG",
      "Farm": "Lettuce",
      "RegistrationNumber": "84059-14",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 10,
      "PerAcreUnits": "quarts",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "4xqx1p8y",
      "ItemName": "Torac",
      "Farm": "Cuke",
      "RegistrationNumber": "71711-31",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 21,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 1,
      "REIHours": 12
    },
    {
      "EntryID": "55292bfd",
      "ItemName": "Nanocrop",
      "Farm": "Cuke",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 2.5,
      "PerAcreUnits": "gallons",
      "PHIDays": 0,
      "REIHours": 0
    },
    {
      "EntryID": "57c4c8c3",
      "ItemName": "Kocid 3000-O",
      "Farm": "Cuke",
      "RegistrationNumber": "91411-11-70051",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 1.25,
      "PerAcreUnits": "pounds",
      "PHIDays": 0,
      "REIHours": 48
    },
    {
      "EntryID": "5a406dd7",
      "ItemName": "Nanocrop",
      "Farm": "Lettuce",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 6.25,
      "PerAcreUnits": "gallons",
      "PHIDays": 0,
      "REIHours": 0
    },
    {
      "EntryID": "5c911e0c",
      "ItemName": "Induce Surfactant",
      "Farm": "Lettuce",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 14,
      "PerAcreUnits": "milliliters",
      "PHIDays": 0,
      "REIHours": 0
    },
    {
      "EntryID": "63124c1e",
      "ItemName": "Kaligreen",
      "Farm": "Cuke",
      "RegistrationNumber": "11581-2",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 2.5,
      "PerAcreUnits": "pounds",
      "PHIDays": 1,
      "REIHours": 4
    },
    {
      "EntryID": "684a7fdc",
      "ItemName": "Kanemite 155C",
      "Farm": "Cuke",
      "RegistrationNumber": "66330-38",
      "ApplicationMethod": "Drip",
      "QuantityPerAcre": 31,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 1,
      "REIHours": 12
    },
    {
      "EntryID": "6acd8132",
      "ItemName": "Floramite",
      "Farm": "Cuke",
      "RegistrationNumber": "400-508-59807",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 16,
      "PerAcreUnits": "ounces",
      "PHIDays": 12,
      "REIHours": 12
    },
    {
      "EntryID": "72df0db6",
      "ItemName": "Afirm Wdg",
      "Farm": "Lettuce",
      "RegistrationNumber": "68173-3-1001",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 15.5,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "792b8ebe",
      "ItemName": "Oxidate 5.0",
      "Farm": "Cuke",
      "RegistrationNumber": "70299-28",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 1,
      "PerAcreUnits": "gallon",
      "PHIDays": 0,
      "REIHours": 1
    },
    {
      "EntryID": "7b6595e9",
      "ItemName": "Hexygon",
      "Farm": "Lettuce",
      "RegistrationNumber": "10163-251",
      "ApplicationMethod": "Fogger",
      "PHIDays": 1,
      "REIHours": 12
    },
    {
      "EntryID": "83b85152",
      "ItemName": "Dipel DF",
      "Farm": "Cuke",
      "RegistrationNumber": "73049-39",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 2,
      "PerAcreUnits": "pounds",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "8539y40t",
      "ItemName": "Luna Sensation",
      "Farm": "Lettuce",
      "RegistrationNumber": "264-1090",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 19,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "8e2113f1",
      "ItemName": "Merivon(R) Xemium(R)",
      "Farm": "Cuke",
      "RegistrationNumber": "7969-310",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 5.5,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "8zdo02bq",
      "ItemName": "Succes",
      "Farm": "Lettuce",
      "RegistrationNumber": "62719-292",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 20,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 1,
      "REIHours": 4
    },
    {
      "EntryID": "95a6b401",
      "ItemName": "Floramite",
      "Farm": "Lettuce",
      "RegistrationNumber": "400-508-59807",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 40,
      "PerAcreUnits": "ounces",
      "PHIDays": 12,
      "REIHours": 12
    },
    {
      "EntryID": "95f45afd",
      "ItemName": "Double Nickle 55",
      "Farm": "Lettuce",
      "RegistrationNumber": "70051-108",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 7.5,
      "PerAcreUnits": "pounds",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "a15e0555",
      "ItemName": "Previcur Flex",
      "Farm": "Cuke",
      "RegistrationNumber": "264-678",
      "ApplicationMethod": "Drip, Spray",
      "QuantityPerAcre": 3,
      "PerAcreUnits": "gallons",
      "PHIDays": 2,
      "REIHours": 12
    },
    {
      "EntryID": "a40016fb",
      "ItemName": "Luna Sensation",
      "Farm": "Cuke",
      "RegistrationNumber": "264-1090",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 7.6,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "a4njirdm",
      "ItemName": "Velum One",
      "Farm": "Cuke",
      "RegistrationNumber": "264-1078",
      "ApplicationMethod": "Spray"
    },
    {
      "EntryID": "a746634b",
      "ItemName": "Gatten",
      "Farm": "Cuke",
      "RegistrationNumber": "11581-6-71711",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 6,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "a79a7ad0",
      "ItemName": "Avid Abamectin .15 EC",
      "Farm": "Lettuce",
      "RegistrationNumber": "100-896",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 40,
      "PerAcreUnits": "fluid_ounces",
      "REIHours": 12
    },
    {
      "EntryID": "ad7f7cca",
      "ItemName": "Flint",
      "Farm": "Cuke",
      "RegistrationNumber": "264-777",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 4,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "b06b7554",
      "ItemName": "Endura",
      "Farm": "Lettuce",
      "RegistrationNumber": "7969-197",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 16.25,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "b0uqo7ig",
      "ItemName": "Triathlon BA",
      "Farm": "Lettuce",
      "RegistrationNumber": "70051-107-59807",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 15,
      "PerAcreUnits": "quarts",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "c735c7bc",
      "ItemName": "Dupont Fontellis",
      "Farm": "Lettuce",
      "RegistrationNumber": "352-834",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 40,
      "PerAcreUnits": "ounces",
      "PHIDays": 1,
      "REIHours": 12
    },
    {
      "EntryID": "c8cdb845",
      "ItemName": "Kaligreen",
      "Farm": "Lettuce",
      "RegistrationNumber": "11581-2",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 6.25,
      "PerAcreUnits": "pounds",
      "PHIDays": 1,
      "REIHours": 4
    },
    {
      "EntryID": "ca1a5f58",
      "ItemName": "Purecrop1",
      "Farm": "Cuke",
      "QuantityPerAcre": 2.5,
      "PerAcreUnits": "gallons"
    },
    {
      "EntryID": "cad836e9",
      "ItemName": "Gatten",
      "Farm": "Lettuce",
      "RegistrationNumber": "11581-6-71711",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 15,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "cc063e6c",
      "ItemName": "Luna Experience",
      "Farm": "Cuke",
      "RegistrationNumber": "264-1091",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 17,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 7,
      "REIHours": 12
    },
    {
      "EntryID": "cqk5m3ff",
      "ItemName": "Azatin O",
      "Farm": "Cuke",
      "RegistrationNumber": "70051-9-59807",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 16,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "d20de3cf",
      "ItemName": "Marrone Bio Venerate CG",
      "Farm": "Lettuce",
      "RegistrationNumber": "84059-14",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 4,
      "PerAcreUnits": "quarts",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "de6b6e41",
      "ItemName": "Debug Turbo",
      "Farm": "Cuke",
      "RegistrationNumber": "1021-2874",
      "ApplicationMethod": "Spray/Drip",
      "REIHours": 4
    },
    {
      "EntryID": "dxxflvon",
      "ItemName": "Beleaf 50 SG",
      "Farm": "Cuke",
      "RegistrationNumber": "71512-10-279",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 2.8,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "e2bcdd3b",
      "ItemName": "Endura",
      "Farm": "Cuke",
      "RegistrationNumber": "7969-197",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 6.5,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "efd30545",
      "ItemName": "Double Nickle 55",
      "Farm": "Cuke",
      "RegistrationNumber": "70051-108",
      "ApplicationMethod": "Drip, Spray",
      "QuantityPerAcre": 3,
      "PerAcreUnits": "pounds",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "f49a8d3d",
      "ItemName": "Debug",
      "Farm": "Cuke",
      "RegistrationNumber": "70310-5",
      "ApplicationMethod": "Drip",
      "QuantityPerAcre": 104,
      "PerAcreUnits": "gallons",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "f55oqwq9",
      "ItemName": "Avid Abamectin .15 EC",
      "Farm": "Cuke",
      "RegistrationNumber": "100-896",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 16,
      "PerAcreUnits": "fluid_ounces",
      "REIHours": 12
    },
    {
      "EntryID": "fb66327a",
      "ItemName": "Kanemite 155C",
      "Farm": "Lettuce",
      "RegistrationNumber": "66330-38",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 77.5,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 1,
      "REIHours": 12
    },
    {
      "EntryID": "fc2a5a82",
      "ItemName": "Flint",
      "Farm": "Lettuce",
      "RegistrationNumber": "264-777",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 10,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "g2omi0pf",
      "ItemName": "Radiant SC",
      "Farm": "Cuke",
      "RegistrationNumber": "62719-545",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 10,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 1,
      "REIHours": 4
    },
    {
      "EntryID": "gc1rqr0e",
      "ItemName": "Zerotol 2.0",
      "Farm": "Lettuce",
      "RegistrationNumber": "70299-12",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 320,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 1
    },
    {
      "EntryID": "ggm795or",
      "ItemName": "Succes",
      "Farm": "Cuke",
      "RegistrationNumber": "62719-292",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 8,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 1,
      "REIHours": 4
    },
    {
      "EntryID": "ipfniza7",
      "ItemName": "Serenade Soil",
      "Farm": "Cuke",
      "RegistrationNumber": "264-1152",
      "ApplicationMethod": "Drip, Spray",
      "QuantityPerAcre": 3.5,
      "PerAcreUnits": "quarts",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "k14wy09v",
      "ItemName": "Afirm Wdg",
      "Farm": "Cuke",
      "RegistrationNumber": "68173-3-1001",
      "ApplicationMethod": "Drip, Spray",
      "QuantityPerAcre": 6.2,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "lvondxxf",
      "ItemName": "Beleaf 50 SG",
      "Farm": "Lettuce",
      "RegistrationNumber": "71512-10-279",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 7,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "mau904sp",
      "ItemName": "Triathlon BA",
      "Farm": "Cuke",
      "RegistrationNumber": "70051-107-59807",
      "QuantityPerAcre": 6,
      "PerAcreUnits": "quarts",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "nibrhdx9",
      "ItemName": "Kocid 3000-O",
      "Farm": "Lettuce",
      "RegistrationNumber": "91411-11-70051",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 3.125,
      "PerAcreUnits": "pounds",
      "PHIDays": 0,
      "REIHours": 48
    },
    {
      "EntryID": "nox223p8",
      "ItemName": "Rally 40Wsp (Mycoinsecticide)",
      "Farm": "Lettuce",
      "RegistrationNumber": "62719-410",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 12.5,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 24
    },
    {
      "EntryID": "o8qhcr3y",
      "ItemName": "Vivando",
      "Farm": "Lettuce",
      "RegistrationNumber": "7969-284",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 38.5,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "pz8gw1e6",
      "ItemName": "Sovran",
      "Farm": "Lettuce",
      "RegistrationNumber": "7969-154",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 12,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "qmv3rdtq",
      "ItemName": "Natural Wet",
      "Farm": "Lettuce",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 40,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 0
    },
    {
      "EntryID": "qr0egc1r",
      "ItemName": "Zerotol 2.0",
      "Farm": "Cuke",
      "RegistrationNumber": "70299-12",
      "ApplicationMethod": "Drip, Spray",
      "QuantityPerAcre": 128,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 1
    },
    {
      "EntryID": "r88g7ox9",
      "ItemName": "Radiant SC",
      "Farm": "Lettuce",
      "RegistrationNumber": "62719-545",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 25,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 1,
      "REIHours": 4
    },
    {
      "EntryID": "t87sw7r2",
      "ItemName": "Tristar 8.5",
      "Farm": "Lettuce",
      "RegistrationNumber": "8033-106-1001",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 0,
      "PHIDays": 7,
      "REIHours": 12
    },
    {
      "EntryID": "tevw9t1w",
      "ItemName": "Vivando",
      "Farm": "Cuke",
      "RegistrationNumber": "7969-284",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 15.4,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "tzvvnboo",
      "ItemName": "Tristar 8.5",
      "Farm": "Cuke",
      "RegistrationNumber": "8033-106-1001",
      "ApplicationMethod": "Spray",
      "PHIDays": 7,
      "REIHours": 12
    },
    {
      "EntryID": "u3wwp830",
      "ItemName": "BotaniGard ES",
      "Farm": "Lettuce",
      "RegistrationNumber": "82074-1",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 3,
      "PerAcreUnits": "quarts",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "u4bqw4fy",
      "ItemName": "Quadris",
      "Farm": "Lettuce",
      "RegistrationNumber": "100-1098",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 38.75,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 1,
      "REIHours": 4
    },
    {
      "EntryID": "unfyqkz1",
      "ItemName": "Serenade Soil",
      "Farm": "Lettuce",
      "RegistrationNumber": "264-1152",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 8.75,
      "PerAcreUnits": "quarts",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "w4smpctr",
      "ItemName": "Torac",
      "Farm": "Lettuce",
      "RegistrationNumber": "71711-31",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 52.5,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 1,
      "REIHours": 12
    },
    {
      "EntryID": "wlqmlhwp",
      "ItemName": "Wrangler",
      "Farm": "Cuke",
      "RegistrationNumber": "34704-931",
      "ApplicationMethod": "Drip",
      "QuantityPerAcre": 0.5,
      "PerAcreUnits": "ounces",
      "PHIDays": 21,
      "REIHours": 12
    },
    {
      "EntryID": "x8nrj5c7",
      "ItemName": "Regalia Biofungicide",
      "Farm": "Lettuce",
      "RegistrationNumber": "84059-3",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 4.75,
      "PerAcreUnits": "gallons",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "y8lymjoq",
      "ItemName": "Azatin O (Lettuce)",
      "Farm": "Cuke",
      "RegistrationNumber": "70051-9-59807",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 8,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 0,
      "REIHours": 4
    },
    {
      "EntryID": "yfxge5pu",
      "ItemName": "Pyganic 5.0",
      "Farm": "Lettuce",
      "RegistrationNumber": "1021-1772",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 255,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 12
    },
    {
      "EntryID": "yp7iu6ll",
      "ItemName": "Rally 40Wsp (Mycoinsecticide)",
      "Farm": "Cuke",
      "RegistrationNumber": "62719-410",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 5,
      "PerAcreUnits": "ounces",
      "PHIDays": 0,
      "REIHours": 24
    },
    {
      "EntryID": "ywe0vnqg",
      "ItemName": "Previcur Flex",
      "Farm": "Lettuce",
      "RegistrationNumber": "264-678",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 7.5,
      "PerAcreUnits": "gallons",
      "PHIDays": 2,
      "REIHours": 12
    },
    {
      "EntryID": "zheo7msj",
      "ItemName": "Oxidate 5.0",
      "Farm": "Lettuce",
      "RegistrationNumber": "70299-28",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 300,
      "PerAcreUnits": "milliliters",
      "PHIDays": 0,
      "REIHours": 0
    },
    {
      "EntryID": "zjyqds5d",
      "ItemName": "Quadris",
      "Farm": "Cuke",
      "RegistrationNumber": "100-1098",
      "ApplicationMethod": "Spray",
      "QuantityPerAcre": 15.5,
      "PerAcreUnits": "fluid_ounces",
      "PHIDays": 1,
      "REIHours": 4
    },
    {
      "EntryID": "zveu5ptj",
      "ItemName": "Wrangler",
      "Farm": "Lettuce",
      "RegistrationNumber": "34704-931",
      "ApplicationMethod": "Fogger",
      "QuantityPerAcre": 1.25,
      "PerAcreUnits": "ounces",
      "PHIDays": 21,
      "REIHours": 12
    }
  ]
};
